export const CategoryData = [
  {
    id: 1,
    categoryTitle: "Background",
    subCategory: [
      { subCatTitle: "Pink" },
      { subCatTitle: "white" },
      { subCatTitle: "orange" },
      { subCatTitle: "aquamarine" },
      { subCatTitle: "blue" },
      { subCatTitle: "gray" },
      { subCatTitle: "light green" },
      { subCatTitle: "yellow" },
    ],
  },
  {
    id: 2,
    categoryTitle: "Clothes",
    subCategory: [
      { subCatTitle: "striped tee" },
      { subCatTitle: "black tee" },
      { subCatTitle: "black hoodie" },
      { subCatTitle: "hawaiian shirt" },
      { subCatTitle: "lumberjack shirt" },
      { subCatTitle: "army jacket" },
      { subCatTitle: "basketball jersey" },
      { subCatTitle: "wool turtleneck" },
      { subCatTitle: "rainbow suspenders" },
      { subCatTitle: "ssof red tee" },
      { subCatTitle: "tie dye shirt" },
      { subCatTitle: "thriller jacket" },
      { subCatTitle: "dark brown" },
      { subCatTitle: "tuxedo" },
      { subCatTitle: "patchwork tweed jacket" },
      { subCatTitle: "leather punk jacket" },
      { subCatTitle: "puffy vest" },
      { subCatTitle: "ssof sleeveless tee" },
      { subCatTitle: "brazil soccer shirt" },
    ],
  },
  {
    id: 3,
    categoryTitle: "Eyes",
    subCategory: [
      { subCatTitle: "chill" },
      { subCatTitle: "ski goggles" },
      { subCatTitle: "holographic" },
      { subCatTitle: "angry" },
      { subCatTitle: "wide eyed" },
      { subCatTitle: "happy" },
      { subCatTitle: "hypnotized" },
      { subCatTitle: "sunglasses" },
      { subCatTitle: "sad" },
      { subCatTitle: "closed" },
      { subCatTitle: "bloodshot" },
      { subCatTitle: "elvis glasses" },
    ],
  },
  {
    id: 4,
    categoryTitle: "Fur",
    subCategory: [
      { subCatTitle: "golden brown" },
      { subCatTitle: "white" },
      { subCatTitle: "cream" },
      { subCatTitle: "brown" },
      { subCatTitle: "blue" },
      { subCatTitle: "lizard" },
      { subCatTitle: "tan" },
      { subCatTitle: "dark brown" },
      { subCatTitle: "psychedelic" },
      { subCatTitle: "red" },
      { subCatTitle: "cheetah" },
    ],
  },
  {
    id: 5,
    categoryTitle: "hat",
    subCategory: [
      { subCatTitle: "red baseball cap" },
      { subCatTitle: "skull cap" },
      { subCatTitle: "queen's crown" },
      { subCatTitle: "bowler" },
      { subCatTitle: "bunny ears" },
      { subCatTitle: "cowboy hat" },
      { subCatTitle: "fedora" },
      { subCatTitle: "safari cap" },
      { subCatTitle: "black baseball cap" },
      { subCatTitle: "girl's dark hair" },
    ],
  },
  {
    id: 6,
    categoryTitle: "mouth",
    subCategory: [
      { subCatTitle: "embarrassed" },
      { subCatTitle: "Grin Cigarette" },
      { subCatTitle: "Chill Bubblegum" },
      { subCatTitle: "Chill Party Horn" },
      { subCatTitle: "Grin" },
      { subCatTitle: "Jovial" },
      { subCatTitle: "Chill Unshaven" },
      { subCatTitle: "Large Grin" },
    ],
  },
  {
    id: 7,
    categoryTitle: "Collection",
    subCategory: [
      {
        subCatTitle: "Genesis",
      },
    ],
  },
];
